### ISSUE TITLE
Output from Python model does not match website

### ISSUE THREAD

**Issue by lol768** [remainvoter/eu2019model#8]
![Screenshot from 2019-05-22 14-22-35](https://user-images.githubusercontent.com/2552726/58177881-0fe6bb80-7c9d-11e9-926d-68b513141e10.png)

And yet, running it locally:

```json
  {
    "recommendation": "Change UK",
    "region": "West Midlands",
    "swing-votes": 114000,
    "pre-dhondt-seats": {
      "Brexit Party": 3,
      "Labour": 1,
      "Liberal Democrats": 1,
      "Conservative": 1,
      "Green": 1
    },
    "post-dhondt-seats": {
      "Brexit Party": 3,
      "Labour": 1,
      "Liberal Democrats": 1,
      "Change UK": 1,
      "Green": 1
    }
  }
```

**Comment by inorton** [comment]
I've seen this too.  I've run with the `--update` option and I see that the database has changed. I think our offline copies are using slightly more recent data than the website

**Comment by lol768** [comment]
Yeah, doesn't inspire much confidence in the site..

**Comment by inorton** [comment]
Latest commit it matches now (or at least does for my region)

**Comment by DrNickMartin** [comment]
Thanks for the comments, these issues were due to a late implementation that I was making locally and didn't commit to the main repo more recently. We made some changes to the engine to bolster regions where remain parties were very close to losing their seat.

All outputs match the website
